---
  auth:
    user: netbox
    password: admin@QCTRD3
  config:
    domain: qct.netbox.io
    ip: 10.108.5.202
  app:
    "Username": "admin"
    "Email": "adam.woolhether@qct.io"
    "Password": "admin@QCT.io"
  ssl:
  #VALUES CAN BE LEFT BLANK
    "Country": "TW"
    "State": "TAOYUAN"
    "Locality": "GUISHAN"
    "Organization": "QCT"
    "Organizational Unit": "RD3/1"
    "Common Name": "qct.netbox.io"
    "Email Address": "adam.woolhether@qct.io"