---
  auth:
    user: netbox
    password: PASSWORD
  config:
    domain: DOMAIN
    ip: 10.x.x.x
  app:
    "Username": "admin"
    "Email": "EMAIL"
    "Password": "PASSWORD"
  ssl:
  #VALUES CAN BE LEFT BLANK
    "Country": " "
    "State": " "
    "Locality": " "
    "Organization": ""
    "Organizational Unit": " "
    "Common Name": " "
    "Email Address": " "