---
- name: INSTALL DEPENDENCIES
  dnf:
    name:
      - epel-release
      - ansible
      - postgresql
      - postgresql-server
      - postgresql-devel
      - gcc
      - python38
      - python38-devel
      - python3-setuptools
      - libxml2-devel
      - libxslt-devel
      - libffi-devel
      - openssl-devel
      - redhat-rpm-config
      - epel-release
      - redis
      - git
      - httpd
      - python3-psycopg2
      - python3-pexpect
    state: latest

- name: UPGRADE PIP TO LATEST
  pip:
    name: pip
    executable: pip3
    state: latest