---
- name: START REDIS SERVICE
  service:
    name: redis
    state: started
    enabled: yes

- name: TEST REDIS SERVICE STATUS
  command: redis-cli ping
  register: redis_resp
  failed_when: redis_resp['stdout'] != "PONG"
  changed_when: false
# - debug:
#     # var: redis_resp
#     msg: Redis response to ping is {{ redis_resp.stdout }}